### ISSUE TITLE
Scope should be configurable

### ISSUE THREAD

**Issue by gokaygurcan** [possibilities/next-github-auth#42]
Hello,

The idea is nice but I might only need the basic profile info rather than the complete list of repositories. It'd be really nice to manage scope at some level. 

Thanks in advance, 
G.

**Comment by possibilities** [comment]
Oh, absolutely! I suppose it should be a prop that you can pass to `src/pages/SignIn`? Any opinion?

**Comment by gokaygurcan** [comment]
Hi again,

It looks like a great solution. Can't think of a better place.

**Comment by possibilities** [comment]
Ah, unfortunately it's not that easy because the `DemandSignin` decorator also needs this value. Going on a brief vision quest, will try to commit something tonight...

**Comment by possibilities** [comment]
Cool, what do you think?

```
import { configureSignIn } from 'next-github-auth'
const SignIn({ scope: 'repo gist' })
export default SignIn
```

**Comment by possibilities** [comment]
Cool, what do you think?

```
import { configureSignIn } from 'next-github-auth'
const SignIn = configureSignIn({ scope: 'repo gist' })
export default SignIn
```

**Comment by gokaygurcan** [comment]
👍 Perfect!

Thanks for this change, I think this is a great improvement. And the solution is really simple and elegant, can't wait to use it in future projects ^_^

**Comment by possibilities** [comment]
🙌
